apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoothjazzapp
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: backend
          image: smoothjazz.azurecr.io/backend:v1
          command: [ "pipenv" ]
          args: [ "run", "python", "server.py" ]
        - name: proxy
          image: smoothjazz.azurecr.io/proxy:v1
          command: [ "./proxy" ]
          args: [ "--backend_addr=localhost:50051", "--backend_tls=False", "--server_tls_cert_file=./misc/localhost.crt", "--server_tls_key_file=./misc/localhost.key", "--allow_all_origins", "--server_http_max_read_timeout=1h", "--server_http_max_write_timeout=1h" ]
          ports:
            - containerPort: 8080
        - name: frontend
          image: smoothjazz.azurecr.io/frontend:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: smoothjazz
  name: smoothjazzservice
spec:
  type: LoadBalancer
  ports:
  - name: proxy
    port: 8080
  - name: frontend
    port: 80
  selector:
    app: app