# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shengji_pb2 as shengji__pb2


class ShengjiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/grpc.testing.Shengji/CreateGame',
                request_serializer=shengji__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.StartGame = channel.unary_unary(
                '/grpc.testing.Shengji/StartGame',
                request_serializer=shengji__pb2.StartGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.StopGame = channel.unary_unary(
                '/grpc.testing.Shengji/StopGame',
                request_serializer=shengji__pb2.StopGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.StreamGame = channel.unary_stream(
                '/grpc.testing.Shengji/StreamGame',
                request_serializer=shengji__pb2.StreamGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.PlayGame = channel.unary_unary(
                '/grpc.testing.Shengji/PlayGame',
                request_serializer=shengji__pb2.PlayGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )


class ShengjiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShengjiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=shengji__pb2.CreateGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=shengji__pb2.StartGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'StopGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StopGame,
                    request_deserializer=shengji__pb2.StopGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'StreamGame': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGame,
                    request_deserializer=shengji__pb2.StreamGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'PlayGame': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayGame,
                    request_deserializer=shengji__pb2.PlayGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.testing.Shengji', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shengji(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/CreateGame',
            shengji__pb2.CreateGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/StartGame',
            shengji__pb2.StartGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/StopGame',
            shengji__pb2.StopGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.testing.Shengji/StreamGame',
            shengji__pb2.StreamGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlayGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/PlayGame',
            shengji__pb2.PlayGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
