# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shengji_pb2 as shengji__pb2


class ShengjiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/grpc.testing.Shengji/CreateGame',
                request_serializer=shengji__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.StartGame = channel.unary_unary(
                '/grpc.testing.Shengji/StartGame',
                request_serializer=shengji__pb2.StartGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.PauseGame = channel.unary_unary(
                '/grpc.testing.Shengji/PauseGame',
                request_serializer=shengji__pb2.PauseGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.ResumeGame = channel.unary_unary(
                '/grpc.testing.Shengji/ResumeGame',
                request_serializer=shengji__pb2.PauseGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.JoinGame = channel.unary_unary(
                '/grpc.testing.Shengji/JoinGame',
                request_serializer=shengji__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.LeaveGame = channel.unary_unary(
                '/grpc.testing.Shengji/LeaveGame',
                request_serializer=shengji__pb2.LeaveGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.EnterRoom = channel.unary_stream(
                '/grpc.testing.Shengji/EnterRoom',
                request_serializer=shengji__pb2.EnterRoomRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.PlayGame = channel.unary_unary(
                '/grpc.testing.Shengji/PlayGame',
                request_serializer=shengji__pb2.PlayGameRequest.SerializeToString,
                response_deserializer=shengji__pb2.Game.FromString,
                )
        self.AddAIPlayer = channel.unary_unary(
                '/grpc.testing.Shengji/AddAIPlayer',
                request_serializer=shengji__pb2.AddAIPlayerRequest.SerializeToString,
                response_deserializer=shengji__pb2.AddAIPlayerResponse.FromString,
                )


class ShengjiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Creates a new game.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Only creator of the game can start/pause/resume a game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """Join a game.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGame(self, request, context):
        """Leaves a game. A player is considered left automatically after 60s of
        inactivity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnterRoom(self, request, context):
        """Returns the game whenever the game state is changed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayGame(self, request, context):
        """Plays a hand
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAIPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShengjiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=shengji__pb2.CreateGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=shengji__pb2.StartGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'PauseGame': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseGame,
                    request_deserializer=shengji__pb2.PauseGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'ResumeGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeGame,
                    request_deserializer=shengji__pb2.PauseGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=shengji__pb2.JoinGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'LeaveGame': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGame,
                    request_deserializer=shengji__pb2.LeaveGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'EnterRoom': grpc.unary_stream_rpc_method_handler(
                    servicer.EnterRoom,
                    request_deserializer=shengji__pb2.EnterRoomRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'PlayGame': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayGame,
                    request_deserializer=shengji__pb2.PlayGameRequest.FromString,
                    response_serializer=shengji__pb2.Game.SerializeToString,
            ),
            'AddAIPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAIPlayer,
                    request_deserializer=shengji__pb2.AddAIPlayerRequest.FromString,
                    response_serializer=shengji__pb2.AddAIPlayerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.testing.Shengji', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shengji(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/CreateGame',
            shengji__pb2.CreateGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/StartGame',
            shengji__pb2.StartGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PauseGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/PauseGame',
            shengji__pb2.PauseGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResumeGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/ResumeGame',
            shengji__pb2.PauseGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/JoinGame',
            shengji__pb2.JoinGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/LeaveGame',
            shengji__pb2.LeaveGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnterRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.testing.Shengji/EnterRoom',
            shengji__pb2.EnterRoomRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlayGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/PlayGame',
            shengji__pb2.PlayGameRequest.SerializeToString,
            shengji__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddAIPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.testing.Shengji/AddAIPlayer',
            shengji__pb2.AddAIPlayerRequest.SerializeToString,
            shengji__pb2.AddAIPlayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
