version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.0
  azure-aks: circleci/azure-aks@0.2.1

parameters:
  image-tag:
    type: string
    default: ci-<< pipeline.number >>

jobs:
  test-backend:
    working_directory: ~/repo/backend
    docker:
      - image: circleci/python:3.8
    resource_class: small
    steps:
      - checkout:
          path: ~/repo
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: backend-pipenv-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv sync
      - save_cache:
          key: backend-pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run: pipenv run python game_state_test.py -v
      - run: pipenv run python server_test.py -v
  test-frontend:
    working_directory: ~/repo/frontend
    docker:
      - image: circleci/node:10-browsers
    resource_class: small
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  push-docker-images:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - azure-acr/build-and-push-image:
          path: ./backend
          login-server-name: smoothjazz.azurecr.io
          registry-name: smoothjazz
          repo: backend
          tag: << pipeline.parameters.image-tag >>
      - azure-acr/build-and-push-image:
          path: ./proxy
          login-server-name: smoothjazz.azurecr.io
          registry-name: smoothjazz
          repo: proxy
          tag: << pipeline.parameters.image-tag >>
      - azure-acr/build-and-push-image:
          path: ./frontend
          login-server-name: smoothjazz.azurecr.io
          registry-name: smoothjazz
          repo: frontend
          tag: << pipeline.parameters.image-tag >>

workflows:
  build:
    jobs:
      - test-backend
      - test-frontend
      - push-docker-images:
          requires:
            - test-backend
            - test-frontend
          filters:
            branches:
              only: main
      - azure-aks/update-container-image:
          cluster-name: smoothjazzapp
          container-image-updates: >-
            backend=smoothjazz.azurecr.io/backend:<< pipeline.parameters.image-tag >>
            proxy=smoothjazz.azurecr.io/proxy:<< pipeline.parameters.image-tag >>
            frontend=smoothjazz.azurecr.io/frontend:<< pipeline.parameters.image-tag >>
          record: true
          resource-group: RhythmicBass
          resource-name: deployment/smoothjazzapp
          show-kubectl-command: true
          requires:
            - push-docker-images
          filters:
            branches:
              only: main
