version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.0
  kubernetes: circleci/kubernetes@0.4.0

parameters:
  image-tag:
    type: string
    default: ci-<< pipeline.number >>

jobs:
  test-backend:
    working_directory: ~/repo/backend
    docker:
      - image: circleci/python:3.8
    resource_class: small
    steps:
      - checkout:
          path: ~/repo
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: backend-pipenv2-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            export PIPENV_VENV_IN_PROJECT="enabled"
            pipenv sync
      - save_cache:
          key: backend-pipenv2-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run: pipenv run python game_state_test.py -v
      - run: pipenv run python server_test.py -v
  test-frontend:
    working_directory: ~/repo/frontend
    docker:
      - image: circleci/node:10-browsers
    resource_class: small
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: frontend-npm-{{ checksum "package-lock.json" }}
      - run: "[[ -d node_modules ]] || npm ci"
      - save_cache:
          key: frontend-npm-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  deploy-aks:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - azure-acr/build-and-push-image:
          path: ./backend
          login-server-name: smoothjazz.azurecr.io
          registry-name: smoothjazz
          repo: backend
          tag: << pipeline.parameters.image-tag >>
      - azure-acr/build-and-push-image:
          path: ./proxy
          login-server-name: smoothjazz.azurecr.io
          registry-name: smoothjazz
          repo: proxy
          tag: << pipeline.parameters.image-tag >>
      - azure-acr/build-and-push-image:
          path: ./frontend
          login-server-name: smoothjazz.azurecr.io
          registry-name: smoothjazz
          repo: frontend
          tag: << pipeline.parameters.image-tag >>
      - kubernetes/install
      - run: az aks get-credentials --name smoothjazzapp --resource-group RhythmicBass
      - kubernetes/update-container-image:
          resource-name: deployment/smoothjazzapp
          container-image-updates: >-
            backend=smoothjazz.azurecr.io/backend:<< pipeline.parameters.image-tag >>
            proxy=smoothjazz.azurecr.io/proxy:<< pipeline.parameters.image-tag >>
            frontend=smoothjazz.azurecr.io/frontend:<< pipeline.parameters.image-tag >>
          record: true
          show-kubectl-command: true

workflows:
  build:
    jobs:
      - test-backend
      - test-frontend
      - deploy-aks:
          requires:
            - test-backend
            - test-frontend
          # filters:
          #   branches:
          #     only: main
