name: Run tests

on:
  workflow_call:

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
          cache: 'pip'
          cache-dependency-path: './server/requirements.txt'
      - run: pip install -r ./server/requirements.txt
      - run: cd ./server && python -m unittest
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './webapp/package-lock.json'
      - run: cd ./webapp && npm ci
      - run: cd ./webapp && npx eslint --max-warnings 0 ./src
      - run: cd ./webapp && CI=true npm test
